name: "Build Containers on Update"

on:
  pull_request: []
#    branches:
#      - update-*
      
jobs:
  spack-containerize:
    runs-on: ubuntu-latest
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Generate spack package Dockerfile
        run: |
           export PATH=/opt/spack/bin:$PATH
           # TODO how do we get package from pull request that needs update?
           branch=$(echo ${GITHUB_REF##*/})
           echo $branch
           package=$(echo "${branch/update-/}")
           package=hdf5
           echo "spack:" > spack.yaml
           echo "  specs: [\"$package\"]" >> spack.yaml
           echo "  view: true" >> spack.yaml

           cat spack.yaml
           # package=$(echo "${GITHUB_BRANCH/update-/}")
           spack containerize
           spack containerize > "${GITHUB_WORKSPACE}/Dockerfile.hdf5"
           
  build-container:
    needs: spack-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Look to see if we have file from container
        run: |
           ls $GITHUB_WORKSPACE
