name: "Build Containers on Update"

on:
  pull_request: []
#    branches:
#      - update-*
      
jobs:
  spack-containerize:
    runs-on: ubuntu-latest
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Generate spack package Dockerfile
        id: dockerize
        run: |
           export PATH=/opt/spack/bin:$PATH
           # TODO how do we get package from pull request that needs update?
           IFS=
           package=hdf5
           echo "spack:" > spack.yaml
           echo "  specs: [\"$package\"]" >> spack.yaml
           echo "  view: true" >> spack.yaml

           cat spack.yaml
           spack containerize > Dockerfile

        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
           
  build-container:
    needs: spack-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile
      - name: Build Dockerfile for package
        run: |
           cat Dockerfile
           ls
           docker build -t ghcr.io/autamus/spacktainer-registry/hdf5:latest .
