name: "Build Containers on Update"

on:
  pull_request: []
#    branches:
#      - update-*
      
jobs:
  spack-containerize:
    runs-on: ubuntu-latest
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Generate spack package Dockerfile
        run: |
           export PATH=/opt/spack/bin:$PATH
           # TODO how do we get package from pull request that needs update?
           package=wget
           echo "spack:" > spack.yaml
           echo "  specs: [\"$package\"]" >> spack.yaml
           echo "  view: true" >> spack.yaml

           cat spack.yaml
           spack containerize > Dockerfile

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
           
  build-container:
    needs: spack-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile

      - name: Docker meta
          id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/autamus/spacktainer-registry
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.BINOC_GIT_USERNAME }}
          password: ${{ secrets.BINOC_GIT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
