name: "Build Containers on Update"

on:
  pull_request: []
#    branches:
#      - update-*
      
jobs:
  spack-containerize:
    runs-on: ubuntu-latest
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Generate spack package Dockerfile
        run: |
           export PATH=/opt/spack/bin:$PATH
           # TODO how do we get package from pull request that needs update?
           package=wget
           echo "spack:" > spack.yaml
           echo "  specs: [\"$package\"]" >> spack.yaml
           echo "  view: true" >> spack.yaml

           cat spack.yaml
           spack containerize > Dockerfile

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
           
  build-container:
    needs: spack-containerize
    runs-on: ubuntu-latest
    steps:
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile
      - name: Build Dockerfile for package
        run: |
           cat Dockerfile
           ls
           # TODO: can use GITHUB_SHA to get tag with commit
           docker build -t ghcr.io/autamus/spacktainer-registry/wget:latest .

      - name: 
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: add commit as tag?
      - name: Push to GitHub Packages
        run: docker push ghcr.io/autamus/spacktainer-registry/wget:latest
